### PR TITLE
Added support for 5.0.1

### PR DESCRIPTION
**Pull request by Wiggen94**
I've added support for 5.0.1 through a custom patch.
This patch only applies to `share/html/Admin/CustomFields/Modify.html`

I've not implemented it for `share/html/Articles/Article/Elements/EditCustomFields` or `share/html/Admin/Queues/Modify.html`

This allows for creation and usage of conditional custom fields.

### CODE REVIEW

**Comment by gibus** [comment]
Great! Many thanks! I'll look at this to merge your pull request as soon as possible (unfortunately I'm over busy this week and the next after…)

**Comment by shahramatrian** [comment]
Thanks for the plugin. Besides updating the patches for RT 5.0.1, I think it needs to be fixed to work with Perl v5.26 and later too. Actually, I tried to install it and faced the following error message:
```
Cannot determine perl version info from lib/RT/Extension/ConditionalCustomFields.pm
Cannot find the location of RT.pm that defines $RT::LocalPath in: inc ...

```
Thanks

**Comment by gibus** [comment]
> Thanks for the plugin. Besides updating the patches for RT 5.0.1, I think it needs to be fixed to work with Perl v5.26 and later too. Actually, I tried to install it and faced the following error message:
> 
> ```
> Cannot determine perl version info from lib/RT/Extension/ConditionalCustomFields.pm
> Cannot find the location of RT.pm that defines $RT::LocalPath in: inc ...
> ```

Hi @shahramatrian ! Actually the plugin has been tested and is working on Perl v5.26.1. The error messages you've reported seems more related to not having $RTHOME set…

**Comment by shahramatrian** [comment]
Thanks @gibus ! Problem solved.

**Comment by metbosch** [comment]
@gibus Any plans to merge this PR?

**Comment by gibus** [comment]
First, I'm very sorry for replying very late. I haven't had any chance to play with RT 5 until last week. I've just published on CPAN RT::Extension::ConditionalCustomFields v1.06 that is now fully compliant with RT 5.0.3.

Beside what was proposed in this Pull Request, I've added patch to `share/html/Articles/Article/Elements/EditCustomFields` and `share/html/Admin/Queues/Modify.html` , update some some stuffs to comply with RT 5 COME upgrade (some HTML has been changed, bootstrap is used, etc.) and fix a bug when dealing with cascaded Select List ConditionalCustomFields.

**Pull request closed without merging**
